version: '3.4'
services:
  oidc-stub:
    build:
      context: oidc-stub
    ports:
      - 8080:8080
    environment:
      DOCKER_COMPOSE: "true"
  loginapp:
    build:
      context: login-app
    ports:
      - 8082:8080
    depends_on:
      - oidc-stub
    environment:
      APP_NAME: "loginapp"
      APP_VERSION: "localhost"
      IDP_DISCOVERY_URL: "http://oidc-stub:8080/.well-known/openid-configuration"
      IDP_CLIENT_ID: "foo"
      IDP_CLIENT_SECRET: "bar"
      AUTH_TOKEN_RESOLVER: "loginapp_ID_token"
      REFRESH_TOKEN_RESOLVER: "loginapp_refresh_token"
      EXPOSED_PORT: "8082"
      DOCKER_COMPOSE: "true"
  frontend:
    build:
      context: go-frontend-image
    ports:
      - 8083:8080
    depends_on:
      - oidc-stub
#      - loginapp
      - echo-server
    environment:
      APP_NAME: "frontend"
      APP_VERSION: "localhost"
      IDP_DISCOVERY_URL: "http://oidc-stub:8080/.well-known/openid-configuration"
      IDP_CLIENT_ID: "foo"
      DELEGATED_LOGIN_URL: "http://localhost:8082/loginapp/api/start"
      AUTH_TOKEN_RESOLVER: "loginapp_ID_token"
      # Just for testing, recommend omitting "CSP_REPORT_ONLY" which will default the value to "false"
      CSP_REPORT_ONLY: "true"
      CSP_DIRECTIVES: "default-src 'self'; script-src 'self';"
      REFERRER_POLICY: "no-referrer"
    volumes:
      - ./test/nginx-env:/var/run/secrets/nais.io/vault/
      - ./test/nginx-proxy:/nginx
  echo-server:
    image: mendhak/http-https-echo
    ports:
      - 8089:80